services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  customer-service:
    build:
      context: ./services/CustomerService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - customer-data:/customerservice.db

  inventory-service:
    build:
      context: ./services/InventoryService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - inventory-data:/inventory.db

  sales-service:
    build:
      context: ./services/SalesService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - sales-data:/sales.db

  order-service:
    build:
      context: ./services/OrderManagementService
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - order-data:/orderservice.db

  vendor-service:
    build:
      context: ./services/VendorService
      dockerfile: Dockerfile
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - vendor-data:/vendor.db

volumes:
  customer-data:
  inventory-data:
  sales-data:
  order-data:
  vendor-data:
