services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  customer-service:
    build:
      context: ./CustomerService
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - customer-data:/customerservice.db 

  inventory-service:
    build:
      context: ./InventoryService
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - inventory-data:/inventory.db 

  sales-service:
    build:
      context: ./SalesService
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - sales-data:/sales.db 

  order-service:
    build:
      context: ./OrderManagementService
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - order-data:/orderservice.db 

  vendor-service:
    build:
      context: ./VendorService
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - vendor-data:/vendor.db

volumes:
  customer-data:
  inventory-data:
  sales-data:
  order-data:
  vendor-data:
