// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxService.Data;

#nullable disable

namespace TaxService.Migrations
{
    [DbContext(typeof(TaxContext))]
    [Migration("20241105142111_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("TaxService.Models.TaxRate", b =>
                {
                    b.Property<int>("TTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CityRate")
                        .HasColumnType("REAL");

                    b.Property<float>("CountyTax")
                        .HasColumnType("REAL");

                    b.Property<float>("StateTax")
                        .HasColumnType("REAL");

                    b.Property<float>("TaxRates")
                        .HasColumnType("REAL");

                    b.Property<int>("TaxYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("TTID");

                    b.ToTable("TaxRates");
                });
#pragma warning restore 612, 618
        }
    }
}
